import Sidebar from "@/components/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/toggle-theme";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inconsolata, Inter } from "next/font/google";
import { unstable_ViewTransition as ViewTransitions } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const inconsolata = Inconsolata({
  variable: "--font-inconsolata-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${inconsolata.variable} ${inter.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex min-h-screen flex-col md:flex-row max-w-7xl mx-auto font-[family-name:var(--font-inter)]">
              <aside className="w-full border-r md:w-80 md:min-h-screen">
                <Sidebar />
              </aside>

              <main className="w-full flex flex-col">
                <header className="p-8">
                  <div className="flex justify-end">
                    <ModeToggle />
                  </div>
                </header>
                <div className="p-8 w-full md:min-h-screen">{children}</div>
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
